#!/usr/bin/env python3
"""Speed benchmark for V100 optimization experiments.
Measures PP tok/s, decode tok/s, TTFT, wall time at multiple context lengths.
"""
import json, sys, time, argparse, subprocess, os

ENDPOINT = os.environ.get("BENCH_ENDPOINT", "http://localhost:8001/v1")
MODEL = os.environ.get("BENCH_MODEL", "qwen")

# Prompts of different sizes - generated by repeating filler text
def make_prompt(target_tokens, seed_text="The quick brown fox jumps over the lazy dog. "):
    # Rough estimate: ~1.3 tokens per word for this text
    words_per_token = 1.3
    chars_per_word = 5
    chars_per_token = chars_per_word / words_per_token
    target_chars = int(target_tokens * chars_per_token)
    text = seed_text
    while len(text) < target_chars:
        text += seed_text
    return text[:target_chars]

def make_coding_prompt(target_tokens):
    """Generate a coding-focused prompt of ~target_tokens."""
    code_lines = [
        "def process_data(items: list[dict]) -> dict:",
        '    """Process a list of items and return aggregated results."""',
        "    results = {}",
        "    for item in items:",
        "        key = item.get('category', 'unknown')",
        "        if key not in results:",
        "            results[key] = {'count': 0, 'total': 0.0, 'items': []}",
        "        results[key]['count'] += 1",
        "        results[key]['total'] += item.get('value', 0.0)",
        "        results[key]['items'].append(item.get('name', ''))",
        "    for key in results:",
        "        r = results[key]",
        "        r['average'] = r['total'] / r['count'] if r['count'] > 0 else 0.0",
        "        r['items'] = sorted(set(r['items']))",
        "    return results",
        "",
    ]
    text = "\n".join(code_lines)
    while len(text) < target_tokens * 4:
        text += "\n" + "\n".join(code_lines)
    return f"Analyze this code for bugs and suggest improvements:\n\n{text[:int(target_tokens * 4)]}"

def run_benchmark(endpoint, model, prompt, max_tokens=128, timeout=600):
    """Run a single benchmark and return timing data."""
    payload = json.dumps({
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": max_tokens,
        "stream": False,
    })

    # Write payload to temp file to avoid ARG_MAX on large prompts
    import tempfile
    tmp = tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False)
    try:
        tmp.write(payload)
        tmp.flush()
        tmp.close()

        start = time.time()
        try:
            result = subprocess.run(
                ["curl", "-fsS", "--max-time", str(timeout),
                 f"{endpoint}/chat/completions",
                 "-H", "Content-Type: application/json",
                 "-d", f"@{tmp.name}"],
                capture_output=True, text=True, timeout=timeout + 30,
            )
        except subprocess.TimeoutExpired:
            return {"status": "TIMEOUT", "wall_time_s": timeout}
        finally:
            wall_time = time.time() - start
    finally:
        os.unlink(tmp.name)

    if result.returncode != 0:
        return {"status": "CURL_ERROR", "wall_time_s": wall_time, "error": result.stderr[:500]}

    try:
        resp = json.loads(result.stdout)
    except json.JSONDecodeError:
        return {"status": "PARSE_ERROR", "wall_time_s": wall_time, "raw": result.stdout[:500]}

    usage = resp.get("usage", {})
    timings = resp.get("timings", {})
    prompt_tokens = usage.get("prompt_tokens", 0)
    completion_tokens = usage.get("completion_tokens", 0)

    # Use timings field from llama.cpp API (ms)
    prompt_ms = timings.get("prompt_ms", 0)
    predicted_ms = timings.get("predicted_ms", 0)
    pp_tps = timings.get("prompt_per_second", 0)
    decode_tps = timings.get("predicted_per_second", 0)

    prompt_eval_duration_s = prompt_ms / 1000
    eval_duration_s = predicted_ms / 1000

    # Fallback: calculate from usage if timings missing
    if pp_tps == 0 and prompt_eval_duration_s > 0:
        pp_tps = prompt_tokens / prompt_eval_duration_s
    if decode_tps == 0 and eval_duration_s > 0:
        decode_tps = completion_tokens / eval_duration_s

    # TTFT ≈ prompt_eval_time (first token comes after PP is done)
    ttft = prompt_eval_duration_s

    content = resp.get("choices", [{}])[0].get("message", {}).get("content", "")
    reasoning = resp.get("choices", [{}])[0].get("message", {}).get("reasoning_content", "")

    return {
        "status": "OK",
        "wall_time_s": round(wall_time, 2),
        "prompt_tokens": prompt_tokens,
        "completion_tokens": completion_tokens,
        "prompt_eval_duration_s": round(prompt_eval_duration_s, 3),
        "eval_duration_s": round(eval_duration_s, 3),
        "prompt_tok_s": round(pp_tps, 1),
        "decode_tok_s": round(decode_tps, 1),
        "ttft_s": round(ttft, 3),
        "content_chars": len(content),
        "reasoning_chars": len(reasoning) if reasoning else 0,
    }

def capture_vram():
    """Capture current VRAM usage."""
    try:
        result = subprocess.run(
            ["nvidia-smi", "--query-gpu=index,memory.used,memory.total,memory.free",
             "--format=csv,noheader,nounits"],
            capture_output=True, text=True,
        )
        gpus = {}
        for line in result.stdout.strip().split("\n"):
            parts = [p.strip() for p in line.split(",")]
            if len(parts) >= 4:
                gpus[f"gpu{parts[0]}"] = {
                    "used_mib": int(parts[1]),
                    "total_mib": int(parts[2]),
                    "free_mib": int(parts[3]),
                }
        return gpus
    except Exception:
        return {}

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--config-id", required=True)
    parser.add_argument("--run-dir", required=True)
    parser.add_argument("--endpoint", default=ENDPOINT)
    parser.add_argument("--model", default=MODEL)
    parser.add_argument("--context-lengths", default="1k,10k,64k,128k")
    parser.add_argument("--repeats-short", type=int, default=3)
    parser.add_argument("--repeats-long", type=int, default=2)
    parser.add_argument("--max-tokens", type=int, default=128)
    parser.add_argument("--timeout", type=int, default=600)
    args = parser.parse_args()

    # Map context length names to approximate token counts
    ctx_map = {
        "1k": 1000,
        "2k": 2000,
        "10k": 10000,
        "64k": 64000,
        "128k": 128000,
        "220k": 220000,
        "250k": 250000,
    }

    results = []

    for ctx_name in args.context_lengths.split(","):
        ctx_name = ctx_name.strip().lower()
        target_tokens = ctx_map.get(ctx_name, int(ctx_name.rstrip("k")) * 1000)

        # Choose prompt generator based on size
        if target_tokens <= 2000:
            prompt = make_prompt(target_tokens)
        else:
            prompt = make_coding_prompt(target_tokens)

        repeats = args.repeats_short if target_tokens <= 10000 else args.repeats_long
        if target_tokens >= 200000:
            repeats = 1  # Very long: single run

        for run_idx in range(repeats):
            run_label = "cold" if run_idx == 0 else "warm"
            print(f"  {args.config_id} | {ctx_name} | {run_label} ({run_idx+1}/{repeats})...", end=" ", flush=True)

            vram_before = capture_vram()
            result = run_benchmark(args.endpoint, args.model, prompt, args.max_tokens, args.timeout)
            vram_after = capture_vram()

            result.update({
                "config_id": args.config_id,
                "prompt_class": ctx_name,
                "run_idx": run_idx,
                "cold_or_warm": run_label,
                "target_tokens": target_tokens,
            })
            result["vram_after"] = vram_after
            results.append(result)

            status = result.get("status", "?")
            pp = result.get("prompt_tok_s", 0)
            dec = result.get("decode_tok_s", 0)
            wall = result.get("wall_time_s", 0)
            pt = result.get("prompt_tokens", 0)
            ct = result.get("completion_tokens", 0)
            print(f"{status} | pt={pt} ct={ct} | PP={pp} dec={dec} | {wall}s")

    # Save results
    out_path = os.path.join(args.run_dir, "results", "raw", f"speed-{args.config_id}.json")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        json.dump(results, f, indent=2)

    # Also append to speed.csv
    csv_path = os.path.join(args.run_dir, "results", "speed.csv")
    write_header = not os.path.exists(csv_path)
    with open(csv_path, "a") as f:
        if write_header:
            f.write("config_id,run_id,cold_or_warm,prompt_class,prompt_tokens,output_tokens,")
            f.write("prompt_tok_s,decode_tok_s,wall_time_s,ttft_s,")
            f.write("gpu0_mem_mib,gpu1_mem_mib,gpu2_mem_mib,status,error\n")
        for r in results:
            vram = r.get("vram_after", {})
            f.write(f"{r.get('config_id','')},{r.get('run_idx','')},{r.get('cold_or_warm','')},")
            f.write(f"{r.get('prompt_class','')},{r.get('prompt_tokens',0)},{r.get('completion_tokens',0)},")
            f.write(f"{r.get('prompt_tok_s',0)},{r.get('decode_tok_s',0)},{r.get('wall_time_s',0):.2f},")
            f.write(f"{r.get('ttft_s',0):.3f},")
            g0 = vram.get("gpu0", {}).get("used_mib", "")
            g1 = vram.get("gpu1", {}).get("used_mib", "")
            g2 = vram.get("gpu2", {}).get("used_mib", "")
            f.write(f"{g0},{g1},{g2},")
            f.write(f"{r.get('status','')},{r.get('error','')}\n")

    print(f"\nResults saved to {out_path}")
    print(f"CSV appended to {csv_path}")

if __name__ == "__main__":
    main()
