#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
STACK_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
MODELS_JSON="$STACK_ROOT/model-suite.models.json"
STACK_ENV="$STACK_ROOT/stack.env"
EVALS_JSON="$STACK_ROOT/model-suite.evals.json"

# ── JSON helpers (use python3 for reliable parsing) ────────────────────────────

json_field() {
  local filter="$1"
  python3 -c "
import json, sys
with open(sys.argv[1]) as f:
    data = json.load(f)
result = $filter
print(result if result is not None else '')
" "$MODELS_JSON"
}

json_list_len() {
  python3 -c "
import json, sys
with open(sys.argv[1]) as f:
    data = json.load(f)
print(len($2))
" "$1"
}

resolve_gguf() {
  local model_id="$1"
  python3 -c "
import json, sys, glob
from pathlib import Path

with open(sys.argv[1]) as f:
    data = json.load(f)

models = {m['id']: m for m in data['models']}
model = models.get(sys.argv[2])
if not model:
    print('', end='')
    sys.exit(1)

pattern = str(Path(model['local_dir']) / model['path_glob'])
matches = sorted(Path(p) for p in glob.glob(pattern, recursive=True))
if matches:
    print(matches[0])
else:
    print('', end='')
    sys.exit(1)
" "$MODELS_JSON" "$model_id"
}

generate_stack_env() {
  local model_id="$1"
  local gguf_path="$2"
  local output="$3"
  python3 -c "
import json, sys, os
from pathlib import Path

with open(sys.argv[1]) as f:
    models_data = json.load(f)

with open(sys.argv[3]) as f:
    evals_data = json.load(f)

base_env_path = Path(evals_data['base_stack_env'])
model_id = sys.argv[2]
gguf_path = Path(sys.argv[4])

models = {m['id']: m for m in models_data['models']}
model = models[model_id]
runtime = model['runtime']

# Parse base env
values = {}
with open(base_env_path) as f:
    for raw in f:
        line = raw.strip()
        if not line or line.startswith('#'):
            continue
        k, v = line.split('=', 1)
        values[k] = v

# Compute mount root
default_models_dir = Path(values['LLAMA_MODELS_HOST_DIR']).resolve()
gguf_resolved = gguf_path.resolve()
mount_root = Path(os.path.commonpath([str(default_models_dir), str(gguf_resolved)]))
rel = gguf_resolved.relative_to(mount_root)

values['LLAMA_MODELS_HOST_DIR'] = str(mount_root)
values['LLAMA_MODEL_PATH'] = f'/models/{rel.as_posix()}'
values['PROXY_REAL_MODEL'] = gguf_path.name
values['LLAMA_CTX_SIZE'] = str(runtime['ctx_size'])
values['LLAMA_PARALLEL'] = str(runtime['parallel'])
values['LLAMA_TENSOR_SPLIT'] = runtime['tensor_split']
values['LLAMA_SPLIT_MODE'] = runtime['split_mode']
values['LLAMA_GPU_LAYERS'] = str(runtime['gpu_layers'])
values['LLAMA_FIT'] = str(runtime['fit'])

lines = ['# Generated by apply-model.sh', '']
for k in sorted(values):
    lines.append(f'{k}={values[k]}')

Path(sys.argv[5]).write_text('\n'.join(lines) + '\n')
" "$MODELS_JSON" "$model_id" "$EVALS_JSON" "$gguf_path" "$output"
}

# ── Commands ───────────────────────────────────────────────────────────────────

cmd_list() {
  python3 -c "
import json
with open('$MODELS_JSON') as f:
    data = json.load(f)
for m in data['models']:
    from pathlib import Path
    import glob
    pattern = str(Path(m['local_dir']) / m['path_glob'])
    matches = sorted(Path(p) for p in glob.glob(pattern, recursive=True))
    installed = 'installed' if matches else 'MISSING'
    gguf = matches[0].name if matches else '-'
    default = '*' if m['id'] in data.get('default_candidate_ids', []) else ' '
    print(f' {default} {m[\"id\"]:40s} {installed:10s} {gguf}')
print()
print('  * = default candidate')
"
}

cmd_current() {
  if [[ ! -f "$STACK_ENV" ]]; then
    echo "No stack.env found"
    return 1
  fi
  local model_path
  model_path=$(grep '^LLAMA_MODEL_PATH=' "$STACK_ENV" | cut -d= -f2-)
  local model_name
  model_name=$(basename "$model_path")
  echo "Current model path: ${model_path}"
  echo "Current model file: ${model_name}"

  local ctx parallel
  ctx=$(grep '^LLAMA_CTX_SIZE=' "$STACK_ENV" | cut -d= -f2-)
  parallel=$(grep '^LLAMA_PARALLEL=' "$STACK_ENV" | cut -d= -f2-)
  echo "Context size: ${ctx:-?}"
  echo "Parallel: ${parallel:-?}"
}

cmd_apply() {
  local model_id="${1:-}"
  local no_rollback=false

  if [[ -z "$model_id" ]]; then
    echo "Usage: apply-model.sh <model-id> [--no-rollback]" >&2
    return 1
  fi

  # Parse flags
  shift || true
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --no-rollback) no_rollback=true ;;
      *) echo "Unknown flag: $1" >&2; return 1 ;;
    esac
    shift
  done

  echo "=== Applying model: ${model_id} ==="

  # Validate model exists in registry
  if ! json_field "next((m for m in data['models'] if m['id']=='${model_id}'), None)" >/dev/null 2>&1; then
    echo "ERROR: model '${model_id}' not found in ${MODELS_JSON}" >&2
    echo "Available models:" >&2
    cmd_list >&2
    return 1
  fi

  # Resolve GGUF
  local gguf_path
  if ! gguf_path=$(resolve_gguf "$model_id"); then
    echo "ERROR: GGUF file not found for model '${model_id}'" >&2
    echo "Run 'bash scripts/model-suite.sh install' first." >&2
    return 1
  fi
  echo "Resolved GGUF: ${gguf_path}"

  if [[ ! -f "$gguf_path" ]]; then
    echo "ERROR: GGUF file does not exist: ${gguf_path}" >&2
    return 1
  fi

  # Backup current config
  local backup=""
  if [[ -f "$STACK_ENV" ]] && [[ "$no_rollback" == "false" ]]; then
    backup="/tmp/stack.env.backup.$(date +%Y%m%d%H%M%S)"
    cp "$STACK_ENV" "$backup"
    echo "Backup saved: ${backup}"
  fi

  # Generate new config
  local tmp_env="/tmp/stack.env.apply.${model_id}.$$"
  if ! generate_stack_env "$model_id" "$gguf_path" "$tmp_env"; then
    echo "ERROR: failed to generate stack.env" >&2
    rm -f "$tmp_env"
    return 1
  fi
  echo "Generated config: ${tmp_env}"

  # Apply: move new config into place and restart
  cp "$tmp_env" "$STACK_ENV"
  rm -f "$tmp_env"

  echo "Restarting V100 stack..."
  if ! STACK_CONFIG_FILE="$STACK_ENV" bash "$SCRIPT_DIR/stack.sh" restart; then
    echo "ERROR: stack restart failed" >&2
    if [[ -n "$backup" ]] && [[ "$no_rollback" == "false" ]]; then
      echo "Rolling back to previous config..."
      cp "$backup" "$STACK_ENV"
      STACK_CONFIG_FILE="$STACK_ENV" bash "$SCRIPT_DIR/stack.sh" restart || true
    fi
    return 1
  fi

  # Wait for readiness
  echo "Waiting for llama.cpp..."
  if ! STACK_CONFIG_FILE="$STACK_ENV" bash "$SCRIPT_DIR/stack.sh" wait-ready 300; then
    echo "ERROR: llama.cpp did not become ready" >&2
    if [[ -n "$backup" ]] && [[ "$no_rollback" == "false" ]]; then
      echo "Rolling back to previous config..."
      cp "$backup" "$STACK_ENV"
      STACK_CONFIG_FILE="$STACK_ENV" bash "$SCRIPT_DIR/stack.sh" restart || true
      STACK_CONFIG_FILE="$STACK_ENV" bash "$SCRIPT_DIR/stack.sh" wait-ready 300 || true
    fi
    return 1
  fi

  # Smoke test
  echo "Running smoke test..."
  if ! STACK_CONFIG_FILE="$STACK_ENV" bash "$SCRIPT_DIR/stack.sh" smoke; then
    echo "ERROR: smoke test failed" >&2
    if [[ -n "$backup" ]] && [[ "$no_rollback" == "false" ]]; then
      echo "Rolling back to previous config..."
      cp "$backup" "$STACK_ENV"
      STACK_CONFIG_FILE="$STACK_ENV" bash "$SCRIPT_DIR/stack.sh" restart || true
      STACK_CONFIG_FILE="$STACK_ENV" bash "$SCRIPT_DIR/stack.sh" wait-ready 300 || true
    fi
    return 1
  fi

  echo "=== Model ${model_id} applied successfully ==="
}

# ── CLI ────────────────────────────────────────────────────────────────────────

usage() {
  cat <<EOF
Usage: $(basename "$0") <command> [options]

Commands:
  list                List available models from model-suite.models.json
  current             Show currently active model config
  apply <model-id>    Apply model: generate config -> restart -> wait -> smoke
                      Rolls back on failure unless --no-rollback is set.

Options:
  --no-rollback       On failure, leave the broken config in place

Examples:
  $(basename "$0") list
  $(basename "$0") apply qwen35-122b-a10b-q4km
  $(basename "$0") apply qwen35-35b-a3b-q5km --no-rollback
EOF
}

cmd="${1:-}"
shift || true

case "$cmd" in
  list)
    cmd_list
    ;;
  current)
    cmd_current
    ;;
  apply)
    cmd_apply "$@"
    ;;
  -h|--help|help)
    usage
    ;;
  *)
    usage
    exit 1
    ;;
esac
