#!/usr/bin/env python3
from __future__ import annotations

import argparse
import copy
import glob
import hashlib
import importlib.util
import json
import os
import shlex
import shutil
import subprocess
import sys
import textwrap
import time
import traceback
import urllib.error
import urllib.request
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


SCRIPT_DIR = Path(__file__).resolve().parent
ROOT_DIR = SCRIPT_DIR.parent
MODELS_CONFIG_PATH = ROOT_DIR / "model-suite.models.json"
EVALS_CONFIG_PATH = ROOT_DIR / "model-suite.evals.json"
STACK_SH_PATH = SCRIPT_DIR / "stack.sh"
STACK_PS1_PATH = SCRIPT_DIR / "stack.ps1"
TRANSIENT_SMOKE_EXIT_CODES = {7, 22, 28, 52, 56}

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(line_buffering=True)
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(line_buffering=True)


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


MODELS_CONFIG = load_json(MODELS_CONFIG_PATH)
EVALS_CONFIG = load_json(EVALS_CONFIG_PATH)


def utc_timestamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def python_cmd() -> list[str]:
    if os.name == "nt":
        launcher = shutil.which("py")
        if launcher:
            return [launcher, "-3"]
        py = shutil.which("python")
        if py:
            return [py]
        raise RuntimeError("Python 3 is required")
    return [shutil.which("python3") or "python3"]


def run_command(
    command: list[str],
    *,
    cwd: Path | None = None,
    env: dict[str, str] | None = None,
    timeout: int | None = None,
    capture: bool = True,
) -> subprocess.CompletedProcess[str]:
    print(f"$ {' '.join(command)}")
    return subprocess.run(
        command,
        cwd=str(cwd) if cwd else None,
        env=env,
        timeout=timeout,
        check=True,
        text=True,
        capture_output=capture,
    )


def print_block(text: str) -> None:
    if not text:
        return
    sys.stdout.write(text)
    if not text.endswith("\n"):
        sys.stdout.write("\n")


def print_process_output(completed: subprocess.CompletedProcess[str] | subprocess.CalledProcessError) -> None:
    print_block(getattr(completed, "stdout", ""))
    print_block(getattr(completed, "stderr", ""))


def exception_payload(exc: BaseException) -> dict[str, Any]:
    return {
        "type": exc.__class__.__name__,
        "message": str(exc),
        "traceback": traceback.format_exception(exc.__class__, exc, exc.__traceback__),
    }


def failed_check_result(exc: BaseException, *, stage: str) -> dict[str, Any]:
    payload = exception_payload(exc)
    return {
        "passed": False,
        "details": [f"{stage}:{payload['type']}: {payload['message']}"],
        "error": payload,
    }


def model_map() -> dict[str, dict[str, Any]]:
    return {item["id"]: item for item in MODELS_CONFIG["models"]}


def select_models(selected: str | None) -> list[dict[str, Any]]:
    models = model_map()
    ids = MODELS_CONFIG["default_candidate_ids"] if not selected else [part.strip() for part in selected.split(",") if part.strip()]
    unknown = [item for item in ids if item not in models]
    if unknown:
        raise SystemExit(f"Unknown model ids: {', '.join(unknown)}")
    return [models[item] for item in ids]


def base_stack_env_path() -> Path:
    return Path(EVALS_CONFIG["base_stack_env"])


def parse_env_file(path: Path) -> dict[str, str]:
    result: dict[str, str] = {}
    with path.open("r", encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            key, value = line.split("=", 1)
            result[key] = value
    return result


def write_env_file(path: Path, values: dict[str, str]) -> None:
    lines = ["# Generated by model_suite.py", ""]
    for key in sorted(values):
        lines.append(f"{key}={values[key]}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def resolve_gguf_on_host(model: dict[str, Any]) -> Path | None:
    pattern = str(Path(model["local_dir"]) / model["path_glob"])
    matches = sorted(Path(item) for item in glob.glob(pattern, recursive=True))
    return matches[0] if matches else None


def is_installed(model: dict[str, Any]) -> bool:
    return resolve_gguf_on_host(model) is not None


def ensure_installed(model: dict[str, Any]) -> Path:
    existing = resolve_gguf_on_host(model)
    if existing:
        return existing

    command = ["hf", "download", model["hf_repo"], "--local-dir", model["local_dir"]]
    for include in model["hf_include"]:
        command.extend(["--include", include])
    completed = run_command(command, timeout=None)
    print_block(completed.stdout)
    print_block(completed.stderr)

    installed = resolve_gguf_on_host(model)
    if not installed:
        raise RuntimeError(f"Model download finished but no GGUF matched {model['path_glob']} under {model['local_dir']}")
    return installed


def stack_env_for_model(model: dict[str, Any], gguf_host_path: Path, output_path: Path) -> Path:
    values = parse_env_file(base_stack_env_path())
    runtime = model["runtime"]
    default_models_dir = Path(values["LLAMA_MODELS_HOST_DIR"]).resolve()
    gguf_resolved = gguf_host_path.resolve()
    mount_root = Path(os.path.commonpath([str(default_models_dir), str(gguf_resolved)]))
    rel = gguf_resolved.relative_to(mount_root)

    values["LLAMA_MODELS_HOST_DIR"] = str(mount_root)
    values["LLAMA_MODEL_PATH"] = f"/models/{rel.as_posix()}"
    values["PROXY_REAL_MODEL"] = gguf_host_path.name
    values["LLAMA_CTX_SIZE"] = str(runtime["ctx_size"])
    values["LLAMA_PARALLEL"] = str(runtime["parallel"])
    values["LLAMA_TENSOR_SPLIT"] = runtime["tensor_split"]
    values["LLAMA_SPLIT_MODE"] = runtime["split_mode"]
    values["LLAMA_GPU_LAYERS"] = str(runtime["gpu_layers"])
    values["LLAMA_FIT"] = str(runtime["fit"])
    write_env_file(output_path, values)
    return output_path


def stack_command(config_file: Path, action: str) -> tuple[list[str], dict[str, str]]:
    env = os.environ.copy()
    env["STACK_CONFIG_FILE"] = str(config_file)
    if os.name == "nt":
        runner = shutil.which("pwsh") or shutil.which("powershell")
        if not runner:
            raise RuntimeError("PowerShell is required to drive the stack on Windows")
        return [runner, "-File", str(STACK_PS1_PATH), action], env
    return ["bash", str(STACK_SH_PATH), action], env


def restart_stack(config_file: Path) -> None:
    command, env = stack_command(config_file, "restart")
    try:
        completed = run_command(command, env=env, timeout=None)
    except subprocess.CalledProcessError as exc:
        print_process_output(exc)
        raise
    print_process_output(completed)


def smoke_stack(config_file: Path, *, timeout_s: int = 900, retry_delay_s: int = 15) -> None:
    command, env = stack_command(config_file, "smoke")
    deadline = time.monotonic() + timeout_s
    attempts = 0
    last_error: subprocess.CalledProcessError | None = None

    while True:
        attempts += 1
        try:
            completed = run_command(command, env=env, timeout=None)
            if attempts > 1:
                print(f"Smoke passed on attempt {attempts}.")
            print_process_output(completed)
            return
        except subprocess.CalledProcessError as exc:
            last_error = exc
            print_process_output(exc)
            if exc.returncode not in TRANSIENT_SMOKE_EXIT_CODES:
                raise
            if time.monotonic() >= deadline:
                raise RuntimeError(
                    f"Stack smoke did not succeed within {timeout_s}s; "
                    f"last exit code={exc.returncode}, attempts={attempts}"
                ) from exc
            print(
                f"Smoke attempt {attempts} failed with transient exit code {exc.returncode}; "
                f"waiting {retry_delay_s}s for the model to become ready..."
            )
            time.sleep(retry_delay_s)

    if last_error is not None:
        raise last_error


def restore_base_stack() -> None:
    print("Restoring base stack configuration...")
    restart_stack(base_stack_env_path())


def api_chat(prompt: str, *, max_tokens: int) -> dict[str, Any]:
    body = json.dumps(
        {
            "model": "qwen",
            "messages": [{"role": "user", "content": prompt}],
            "max_tokens": max_tokens,
            "stream": False,
        }
    ).encode("utf-8")
    request = urllib.request.Request(
        "http://127.0.0.1:4001/v1/chat/completions",
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    started = time.time()
    try:
        with urllib.request.urlopen(request, timeout=600) as response:
            raw = response.read().decode("utf-8")
    except urllib.error.URLError as exc:
        raise RuntimeError(f"API call failed: {exc}") from exc
    finished = time.time()
    payload = json.loads(raw)
    payload["wall_time_s"] = round(finished - started, 6)
    return payload


def run_direct_benchmarks() -> list[dict[str, Any]]:
    results: list[dict[str, Any]] = []
    for item in EVALS_CONFIG["direct_benchmarks"]:
        payload = api_chat(item["prompt"], max_tokens=int(item["max_tokens"]))
        if not item.get("record", True):
            continue
        timings = payload.get("timings", {})
        results.append(
            {
                "id": item["id"],
                "wall_time_s": payload["wall_time_s"],
                "prompt_tokens": payload.get("usage", {}).get("prompt_tokens"),
                "completion_tokens": payload.get("usage", {}).get("completion_tokens"),
                "prompt_ms": timings.get("prompt_ms"),
                "prompt_per_second": timings.get("prompt_per_second"),
                "predicted_ms": timings.get("predicted_ms"),
                "predicted_per_second": timings.get("predicted_per_second"),
                "content": payload["choices"][0]["message"]["content"],
            }
        )
    return results


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def copy_fixture(case: dict[str, Any], target_dir: Path) -> None:
    source = Path(EVALS_CONFIG["fixture_root"]) / case["fixture"]
    shutil.copytree(source, target_dir, dirs_exist_ok=False)


def session_list() -> list[dict[str, str]]:
    completed = run_command(["opencode", "session", "list"])
    rows = completed.stdout.splitlines()[2:]
    results: list[dict[str, str]] = []
    for row in rows:
        stripped = row.strip()
        if not stripped:
            continue
        parts = stripped.split()
        session_id = parts[0]
        updated = " ".join(parts[-2:])
        title = " ".join(parts[1:-2])
        results.append({"id": session_id, "title": title, "updated": updated})
    return results


def find_session_by_title(title: str) -> str:
    for item in session_list():
        if item["title"] == title:
            return item["id"]
    raise RuntimeError(f"Unable to locate OpenCode session with title: {title}")


def export_session(session_id: str, *, attempts: int = 5, retry_delay_s: int = 2) -> dict[str, Any]:
    last_error: Exception | None = None
    for attempt in range(1, attempts + 1):
        completed = run_command(["opencode", "export", session_id])
        raw = completed.stdout
        json_start = raw.find("{")
        if json_start < 0:
            last_error = RuntimeError(f"Could not parse export output for session {session_id}")
        else:
            try:
                return json.loads(raw[json_start:])
            except json.JSONDecodeError as exc:
                last_error = exc
        if attempt >= attempts:
            break
        print(
            f"Export parse for session {session_id} failed on attempt {attempt}; "
            f"waiting {retry_delay_s}s before retry..."
        )
        time.sleep(retry_delay_s)
    assert last_error is not None
    raise last_error


def build_opencode_run_command(case_dir: Path, title: str, prompt: str) -> list[str]:
    print_logs = os.environ.get("MODEL_SUITE_PRINT_LOGS", "").strip().lower() in {"1", "true", "yes", "on"}
    command = [
        "opencode",
        "run",
        "--dir",
        str(case_dir),
        "--title",
        title,
        "--dangerously-skip-permissions",
        prompt,
    ]
    if print_logs:
        command.insert(-2, "--print-logs")
    if os.name != "nt" and shutil.which("script"):
        return ["script", "-q", "-e", "-c", shlex.join(command), "/dev/null"]
    return command


def opencode_run(case_dir: Path, title: str, prompt: str, timeout_seconds: int) -> str:
    command = build_opencode_run_command(case_dir, title, prompt)
    try:
        completed = run_command(command, timeout=timeout_seconds, capture=True)
    except subprocess.CalledProcessError as exc:
        print_process_output(exc)
        raise
    print_process_output(completed)
    return find_session_by_title(title)


def run_visible_tests(case_dir: Path) -> dict[str, Any]:
    command = python_cmd() + ["-m", "unittest", "discover", "-s", "tests", "-v"]
    try:
        completed = run_command(command, cwd=case_dir)
        output = completed.stdout + completed.stderr
        passed = "OK" in output and "FAILED" not in output
        return {"passed": passed, "output": output, "returncode": completed.returncode}
    except subprocess.CalledProcessError as exc:
        print_process_output(exc)
        output = (exc.stdout or "") + (exc.stderr or "")
        return {
            "passed": False,
            "output": output,
            "returncode": exc.returncode,
            "error": exception_payload(exc),
        }


def import_from_path(module_name: str, file_path: Path):
    spec = importlib.util.spec_from_file_location(module_name, str(file_path))
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot import module from {file_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)  # type: ignore[attr-defined]
    return module


def hidden_check_ttl_cache(case_dir: Path) -> dict[str, Any]:
    module = import_from_path("ttl_cache_hidden", case_dir / "ttl_cache.py")

    class Clock:
        def __init__(self):
            self.t = 0.0

        def now(self):
            return self.t

        def advance(self, seconds: float):
            self.t += seconds

    clock = Clock()
    cache = module.TTLCache(maxsize=2, ttl_seconds=10, now_func=clock.now)
    cache.set("a", 1, ttl_seconds=100)
    cache.set("b", 2, ttl_seconds=1)
    clock.advance(2)
    cache.set("c", 3)
    a_value = cache.get("a")
    b_value = cache.get("b")
    c_value = cache.get("c")
    passed = a_value == 1 and b_value is None and c_value == 3
    return {
        "passed": passed,
        "details": {
            "a": a_value,
            "b": b_value,
            "c": c_value,
        },
    }


def hidden_check_env_template(case_dir: Path) -> dict[str, Any]:
    module = import_from_path("env_template_hidden", case_dir / "env_template.py")
    result = module.resolve_templates({"A": "${B}", "B": "", "OUT": "${A:-fallback}"})
    passed = result["OUT"] == "fallback"
    return {"passed": passed, "details": result}


def hidden_check_json_patch(case_dir: Path) -> dict[str, Any]:
    module = import_from_path("json_patch_hidden", case_dir / "json_patch.py")
    issues: list[str] = []

    replaced = module.apply_patch({"items": [1, 2, 3]}, [{"op": "replace", "path": "/items/1", "value": 99}])
    if replaced["items"] != [1, 99, 3]:
        issues.append(f"replace_list={replaced['items']}")

    try:
        added = module.apply_patch({"a": 1}, [{"op": "add", "path": "/b", "value": None}])
        if added["b"] is not None:
            issues.append(f"add_none={added}")
    except Exception as exc:  # pragma: no cover - report as benchmark output
        issues.append(f"add_none_raised={exc}")

    return {"passed": not issues, "details": issues or ["ok"]}


HIDDEN_CHECKS = {
    "ttl_cache_expired_lru": hidden_check_ttl_cache,
    "env_template_default_on_resolved_empty": hidden_check_env_template,
    "json_patch_semantics": hidden_check_json_patch,
}


def run_hidden_check(hidden_name: str, case_dir: Path) -> dict[str, Any]:
    try:
        return HIDDEN_CHECKS[hidden_name](case_dir)
    except Exception as exc:  # pragma: no cover - exercised by suite on real model failures
        return failed_check_result(exc, stage=f"hidden_check:{hidden_name}")


def collect_session_metrics(session: dict[str, Any]) -> dict[str, Any]:
    assistants = [message for message in session["messages"] if message["info"]["role"] == "assistant"]
    first = assistants[0]["info"]["time"]["created"]
    last = assistants[-1]["info"]["time"]["completed"]
    final_text = ""
    for part in assistants[-1]["parts"]:
        if part.get("type") == "text":
            final_text = part["text"]
            break
    return {
        "turns": len(assistants),
        "wall_s": round((last - first) / 1000, 3),
        "input_tokens": sum(item["info"]["tokens"]["input"] for item in assistants),
        "output_tokens": sum(item["info"]["tokens"]["output"] for item in assistants),
        "cache_read_tokens": sum(item["info"]["tokens"]["cache"]["read"] for item in assistants),
        "final_text": final_text,
    }


def empty_session_metrics() -> dict[str, Any]:
    return {
        "turns": 0,
        "wall_s": None,
        "input_tokens": 0,
        "output_tokens": 0,
        "cache_read_tokens": 0,
        "final_text": "",
    }


def evaluate_case(run_root: Path, model_id: str, case: dict[str, Any]) -> dict[str, Any]:
    case_dir = run_root / model_id / "cases" / case["id"]
    case_dir.parent.mkdir(parents=True, exist_ok=True)
    copy_fixture(case, case_dir)

    fixture_dir = Path(EVALS_CONFIG["fixture_root"]) / case["fixture"]
    fixture_hashes = {str(path.relative_to(fixture_dir)): sha256_file(path) for path in fixture_dir.rglob("*.py")}

    title = f"{run_root.name}-{model_id}-{case['id']}"
    session_id: str | None = None
    session: dict[str, Any] | None = None
    session_metrics = empty_session_metrics()
    case_errors: list[dict[str, Any]] = []

    try:
        session_id = opencode_run(case_dir, title, case["prompt"], int(case["timeout_seconds"]))
    except Exception as exc:
        case_errors.append({"stage": "opencode_run", **exception_payload(exc)})

    if session_id is not None:
        try:
            session = export_session(session_id)
            session_metrics = collect_session_metrics(session)
        except Exception as exc:
            case_errors.append({"stage": "export_session", **exception_payload(exc)})

    visible = run_visible_tests(case_dir)

    workspace_hashes = {str(path.relative_to(case_dir)): sha256_file(path) for path in case_dir.rglob("tests/*.py")}
    hashes_unchanged = all(workspace_hashes.get(rel) == digest for rel, digest in fixture_hashes.items() if rel.startswith("tests/"))

    hidden_name = case["hidden_check"]
    hidden = run_hidden_check(hidden_name, case_dir)

    if session is not None:
        export_path = run_root / model_id / "exports" / f"{case['id']}.json"
        export_path.parent.mkdir(parents=True, exist_ok=True)
        export_path.write_text(json.dumps(session, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    return {
        "id": case["id"],
        "session_id": session_id,
        "session_title": title,
        "metrics": session_metrics,
        "visible_tests": visible,
        "test_hashes_unchanged": hashes_unchanged,
        "hidden_check": hidden,
        "case_dir": str(case_dir),
        "solution_file": case["solution_file"],
        "errors": case_errors,
    }


def compare_results(results: dict[str, Any], output_dir: Path) -> tuple[Path, Path]:
    summary_json = output_dir / "summary.json"
    summary_md = output_dir / "summary.md"
    summary_json.write_text(json.dumps(results, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    lines = [
        "# Model Suite Summary",
        "",
        f"Run ID: `{results['run_id']}`",
        "",
    ]
    for model_result in results["models"]:
        lines.extend(
            [
                f"## {model_result['label']}",
                "",
                f"- Model ID: `{model_result['id']}`",
                f"- GGUF: `{model_result['gguf_name']}`",
                f"- Direct benchmarks:",
            ]
        )
        for bench in model_result["direct_benchmarks"]:
            lines.append(
                f"  - `{bench['id']}`: wall={bench['wall_time_s']}s, prompt/s={bench['prompt_per_second']}, decode/s={bench['predicted_per_second']}"
            )
        lines.append("- Eval cases:")
        for case in model_result["cases"]:
            suffix = ""
            if case.get("errors"):
                stages = ",".join(item["stage"] for item in case["errors"])
                suffix = f", errors={stages}"
            lines.append(
                f"  - `{case['id']}`: visible={case['visible_tests']['passed']}, hidden={case['hidden_check']['passed']}, wall={case['metrics']['wall_s']}s, turns={case['metrics']['turns']}{suffix}"
            )
        if model_result.get("error"):
            lines.append(
                f"- Model error: `{model_result['error']['type']}: {model_result['error']['message']}`"
            )
        lines.append("")

    summary_md.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return summary_json, summary_md


def run_model_suite(selected_models: list[dict[str, Any]], *, run_id: str, install_missing: bool, restore_base: bool) -> dict[str, Any]:
    results_root = Path(EVALS_CONFIG["results_root"])
    run_root = results_root / run_id
    run_root.mkdir(parents=True, exist_ok=True)
    results: dict[str, Any] = {"run_id": run_id, "models": []}

    try:
        for model in selected_models:
            print(f"=== MODEL {model['id']} ===")
            gguf: Path | None = None
            generated_env: Path | None = None
            try:
                gguf = ensure_installed(model) if install_missing else resolve_gguf_on_host(model)
                if gguf is None:
                    raise RuntimeError(f"Model {model['id']} is not installed and install_missing=false")

                model_dir = run_root / model["id"]
                model_dir.mkdir(parents=True, exist_ok=True)
                generated_env = stack_env_for_model(model, gguf, model_dir / "stack.env")

                restart_stack(generated_env)
                smoke_stack(generated_env)

                direct = run_direct_benchmarks()
                cases = [evaluate_case(run_root, model["id"], case) for case in EVALS_CONFIG["cases"]]
                results["models"].append(
                    {
                        "id": model["id"],
                        "label": model["label"],
                        "gguf_name": gguf.name,
                        "generated_stack_env": str(generated_env),
                        "direct_benchmarks": direct,
                        "cases": cases,
                    }
                )
            except Exception as exc:
                print(f"Model {model['id']} failed: {exc.__class__.__name__}: {exc}")
                results["models"].append(
                    {
                        "id": model["id"],
                        "label": model["label"],
                        "gguf_name": gguf.name if gguf else "",
                        "generated_stack_env": str(generated_env) if generated_env else "",
                        "direct_benchmarks": [],
                        "cases": [],
                        "error": exception_payload(exc),
                    }
                )
                continue
    finally:
        if restore_base:
            restore_base_stack()

    compare_results(results, run_root)
    return results


def cmd_list_models(args: argparse.Namespace) -> int:
    for model in MODELS_CONFIG["models"]:
        installed = resolve_gguf_on_host(model)
        print(f"{model['id']}\t{model['label']}\tinstalled={'yes' if installed else 'no'}\tpath={installed or '-'}")
    return 0


def cmd_list_cases(args: argparse.Namespace) -> int:
    for case in EVALS_CONFIG["cases"]:
        print(f"{case['id']}\tfixture={case['fixture']}\thidden_check={case['hidden_check']}")
    return 0


def cmd_plan(args: argparse.Namespace) -> int:
    models = select_models(args.models)
    run_id = args.run_id or f"plan-{utc_timestamp()}"
    print(f"Run ID: {run_id}")
    print("Selected models:")
    for model in models:
        installed = resolve_gguf_on_host(model)
        print(
            textwrap.dedent(
                f"""\
                - {model['id']}
                  label: {model['label']}
                  installed: {'yes' if installed else 'no'}
                  repo: {model['hf_repo']}
                  local_dir: {model['local_dir']}
                  path_glob: {model['path_glob']}
                  ctx: {model['runtime']['ctx_size']}
                  tensor_split: {model['runtime']['tensor_split']}
                """
            ).rstrip()
        )
    print("Cases:")
    for case in EVALS_CONFIG["cases"]:
        print(f"- {case['id']} (timeout={case['timeout_seconds']}s, hidden={case['hidden_check']})")
    return 0


def cmd_install(args: argparse.Namespace) -> int:
    for model in select_models(args.models):
        print(f"Installing/checking {model['id']} ...")
        gguf = ensure_installed(model)
        print(f"Resolved GGUF: {gguf}")
    return 0


def cmd_run(args: argparse.Namespace) -> int:
    models = select_models(args.models)
    run_id = args.run_id or f"run-{utc_timestamp()}"
    results = run_model_suite(models, run_id=run_id, install_missing=not args.skip_install, restore_base=not args.no_restore)
    print(json.dumps(results, indent=2, ensure_ascii=False))
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Install, benchmark, and compare local GGUF coding models.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    subparsers.add_parser("list-models", help="List configured model candidates.")
    subparsers.add_parser("list-cases", help="List configured eval cases.")

    plan_parser = subparsers.add_parser("plan", help="Show which models and cases will run.")
    plan_parser.add_argument("--models", help="Comma-separated model ids. Defaults to default_candidate_ids.")
    plan_parser.add_argument("--run-id", help="Optional run id.")

    install_parser = subparsers.add_parser("install", help="Download configured models if missing.")
    install_parser.add_argument("--models", help="Comma-separated model ids. Defaults to default_candidate_ids.")

    run_parser = subparsers.add_parser("run", help="Run full benchmark/eval suite.")
    run_parser.add_argument("--models", help="Comma-separated model ids. Defaults to default_candidate_ids.")
    run_parser.add_argument("--run-id", help="Optional run id.")
    run_parser.add_argument("--skip-install", action="store_true", help="Do not download missing models.")
    run_parser.add_argument("--no-restore", action="store_true", help="Leave the last tested model running instead of restoring the base stack.")

    full_parser = subparsers.add_parser("full", help="Alias for run.")
    full_parser.add_argument("--models", help="Comma-separated model ids. Defaults to default_candidate_ids.")
    full_parser.add_argument("--run-id", help="Optional run id.")
    full_parser.add_argument("--skip-install", action="store_true", help="Do not download missing models.")
    full_parser.add_argument("--no-restore", action="store_true", help="Leave the last tested model running instead of restoring the base stack.")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.command == "list-models":
        return cmd_list_models(args)
    if args.command == "list-cases":
        return cmd_list_cases(args)
    if args.command == "plan":
        return cmd_plan(args)
    if args.command == "install":
        return cmd_install(args)
    if args.command in {"run", "full"}:
        return cmd_run(args)
    parser.error(f"Unsupported command: {args.command}")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
